name: pihole
services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: ${PIHOLE_CONTAINER_NAME}
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    # Admin interface is on the internal port 80
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
    # Volumes store your data between container upgrades
    volumes:
      - './data/pihole/volumes/pihole:/etc/pihole'
      - './data/pihole/volumes/dnsmasq:/etc/dnsmasq.d'
      - './data/pihole/volumes/export:/export'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      - pihole

networks:
  pihole:
    name: pihole
    driver: bridge