name: nginx
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/config/certs/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./data/nginx/config/certs/server.key.nopass:/etc/nginx/ssl/server.key:ro
      - ./data/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/config/html:/usr/share/nginx/html:ro
      - ./data/nginx/config/certs:/etc/nginx/certs:ro
    networks:
      - nginx
      - activepieces
      - appsmith
      - currency_convert
      - duplicati
      - flowise
      - giles
      - langfuse
      - metabase
      #- mongodb
      - paperless
      - pihole
      - postgres
networks:
  nginx:
    name: nginx
    driver: bridge
  activepieces:
    external: true
  appsmith:
    external: true
  currency_convert:
    external: true
  duplicati:
    external: true
  flowise:
    external: true
  giles:
    external: true
  langfuse:
    external: true
  metabase:
    external: true
  #mongodb:
    #external: true
  paperless:
    external: true
  pihole:
    external: true
  postgres:
    external: true
